# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08b9cea9df4d5e4a8c03e73525edf3178ecf3a8dd649d9411255c0c706ea2d0cc285d7ba346d69de44d59ce5b213f0fa22cf691e6dc1c327bc039dc55801a05d

test:
  secret_key_base: c57f269a44fbfbc51945f16a80e28dcf6e6d0656d90bb4a69fb6cccdf6660bd91659f92f5165e3f0ab82d0334a84efedc0c2e9481016c08ba6a2de89a330f7f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 3f97e8f0cad03f7a954e54d47d4a8aa480aa92355f74b7ae347ebacc514202a59df6faec7f9b9444fd4d08f4a3e9aaf76409509d247d02c7ffde6029267d4a63
